spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inflearn_spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: big
    password: big
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  batch:
    job:
      names: ${job.name:NONE} # --job.name={batchName}
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
          descriptor:
            sql: trace
